### ISSUE TITLE
CREATE EXTENSION ap_pgutils - /usr/lib/postgresql/ap_pgutils.so: undefined symbol: secure_wipe_memory

### ISSUE THREAD

**Issue by carlos-moreira** [Apsalar/ap_pgutils#1]
Hello, I'm trying to install this extension on my Arch Linux x86_64 machine, and after installing some dependencies:

- clang15
- llvm15

And updating the file GNUmakefile to point to the right PG_HOME, I've finally managed to run the commands make, and make install, successfully.

After that I tried to run CREATE EXTENSION ap_pgutils, and got this error message:
`/usr/lib/postgresql/ap_pgutils.so: undefined symbol: secure_wipe_memory`

Is it because this extension might not be compatible with my version of Postgres?

Some logs to help:

```
$ ldd ap_pgutils.so
        linux-vdso.so.1 (0x00007ffe99786000)
        libargon2.so.1 => /usr/lib/libargon2.so.1 (0x00007ff2e37f0000)
        libcrypto.so.3 => /usr/lib/libcrypto.so.3 (0x00007ff2e3200000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007ff2e301e000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007ff2e3834000)


SELECT version();
                                        version                                        
---------------------------------------------------------------------------------------
 PostgreSQL 15.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 13.2.1 20230801, 64-bit
(1 row)
```

**Comment by fazalmajid** [comment]
No, `secure_wipe_memory` is a function provided by https://github.com/Apsalar/phc-winner-argon2. That function still exists but isn't called any more in the active version of the argon2 lib, so your build linked against the system-supplied libargon2 that no longer defines the symbol rather than the bundled Apsalar version the ap_pgutils makefile tries to link against, and indeed that's what your ldd shows.

Try editing `GNUmakefile` and change the line:

```
COMMON_CFLAGS=	-g -O0
```

```
COMMON_CFLAGS=	-g -O0 -Dsecure_wipe_memory=explicit_bzero
```

**Comment by carlos-moreira** [comment]
Thank you, it worked!

I was able to execute the command CREATE EXTENSION ap_pgutils successfully now, but when I tried to test the function argon2, I got a segmentation fault error:

```
# SELECT argon2('123456', 'salt');
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
The connection to the server was lost. Attempting reset: Failed.
```

I tried executing make test to run the tests, and here is what I got:

```
$ make test
init DB
rm -rf testdata
/usr/bin/initdb testdata >/dev/null 2>&1
load extension
tr '\n' ' ' < ap_pgutils.sql|sed -e s@.libdir@`pwd`@g|/usr/bin/postgres --single -D testdata postgres

PostgreSQL stand-alone backend 15.4
backend> backend> 2023-12-11 12:11:45.691 -03 [11055] LOG:  checkpoint starting: shutdown immediate
2023-12-11 12:11:45.697 -03 [11055] LOG:  checkpoint complete: wrote 22 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.002 s, sync=0.003 s, total=0.007 s; sync files=12, longest=0.001 s, average=0.001 s; distance=95 kB, estimate=95 kB

test extension
echo 'select gethostname();'|/usr/bin/postgres --single -D testdata postgres

PostgreSQL stand-alone backend 15.4
backend>         1: gethostname (typeid = 25, len = -1, typmod = -1, byval = f)
        ----
         1: gethostname = "carlos-moreira"      (typeid = 25, len = -1, typmod = -1, byval = f)
        ----
backend> 2023-12-11 12:11:45.730 -03 [11061] LOG:  checkpoint starting: shutdown immediate
2023-12-11 12:11:45.735 -03 [11061] LOG:  checkpoint complete: wrote 4 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.002 s, sync=0.002 s, total=0.006 s; sync files=3, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
echo "select argon2('password', 'somesalt', 2, 16, 24, 'i');"|/usr/bin/postgres --single -D testdata postgres

PostgreSQL stand-alone backend 15.4
backend>         1: argon2      (typeid = 25, len = -1, typmod = -1, byval = f)
        ----
make: *** [GNUmakefile:42: test] Error 139
```

Do you know what steps I must try to debug it? I can try them and post here the results.

**Comment by fazalmajid** [comment]
Did it dump core? You could run `gdb /usr/bin/postgres core` then type `bt` to get a backtrace.

I'm currently on PG 16, the extension fails to build with a different error so I can't reproduce until I fix the issue.

**Comment by carlos-moreira** [comment]
It didn't generate the dump core, but I followed the instructions described here: https://wiki.postgresql.org/wiki/Getting_a_stack_trace_of_a_running_PostgreSQL_backend_on_Linux/BSD#Attaching_gdb_to_the_backend

And I was able to log the error:

```
$ cat debuglog.txt 
Breakpoint 1 at 0x563cdf72a4b0
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0x00007fa527378edd in ?? () from target:/usr/lib/libc.so.6
Detaching from program: target:/usr/bin/postgres, process 15186
[Inferior 1 (process 15186) detached]
```

It seems the problem is related to the libc.so.6 lib

I forgot to log the bt command, here is what I got:

```
(gdb) cont
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0x00007fa527378edd in ?? () from target:/usr/lib/libc.so.6
(gdb) bt
#0  0x00007fa527378edd in ?? () from target:/usr/lib/libc.so.6
#1  0x00007fa52708c16f in argon2_encodedlen () from target:/usr/lib/libargon2.so.1
#2  0x00007fa52715e58e in pg_argon2 (fcinfo=0x563ce0f65738) at /home/carloshmm/ap_pgutils/ap_pgutils.c:112
#3  0x0000563cdf431c53 in ?? ()
#4  0x0000563cdf51bcbc in evaluate_expr ()
#5  0x0000563cdf51bf5e in ?? ()
#6  0x0000563cdf51cf3f in ?? ()
#7  0x0000563cdf4ada24 in expression_tree_mutator ()
#8  0x0000563cdf4ae514 in expression_tree_mutator ()
#9  0x0000563cdf5003f2 in ?? ()
#10 0x0000563cdf505c1b in subquery_planner ()
#11 0x0000563cdf4ff384 in standard_planner ()
#12 0x0000563cdf5d6566 in pg_plan_query ()
#13 0x0000563cdf5d65d4 in pg_plan_queries ()
#14 0x0000563cdf5d9324 in ?? ()
#15 0x0000563cdf5db933 in PostgresMain ()
#16 0x0000563cdf547f8c in ?? ()
#17 0x0000563cdf54919a in PostmasterMain ()
#18 0x0000563cdf251ac2 in main ()
```

This is the content of line 112 of the file ap_pgutils/ap_pgutils.c
`encodedlen = argon2_encodedlen(t_cost, m_cost, 1, saltlen, outlen);`

**Comment by carlos-moreira** [comment]
I forgot to log the bt command, here is what I got:

```
(gdb) cont
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0x00007fa527378edd in ?? () from target:/usr/lib/libc.so.6
(gdb) bt
#0  0x00007fa527378edd in ?? () from target:/usr/lib/libc.so.6
#1  0x00007fa52708c16f in argon2_encodedlen () from target:/usr/lib/libargon2.so.1
#2  0x00007fa52715e58e in pg_argon2 (fcinfo=0x563ce0f65738) at /home/carloshmm/ap_pgutils/ap_pgutils.c:112
#3  0x0000563cdf431c53 in ?? ()
#4  0x0000563cdf51bcbc in evaluate_expr ()
#5  0x0000563cdf51bf5e in ?? ()
#6  0x0000563cdf51cf3f in ?? ()
#7  0x0000563cdf4ada24 in expression_tree_mutator ()
#8  0x0000563cdf4ae514 in expression_tree_mutator ()
#9  0x0000563cdf5003f2 in ?? ()
#10 0x0000563cdf505c1b in subquery_planner ()
#11 0x0000563cdf4ff384 in standard_planner ()
#12 0x0000563cdf5d6566 in pg_plan_query ()
#13 0x0000563cdf5d65d4 in pg_plan_queries ()
#14 0x0000563cdf5d9324 in ?? ()
#15 0x0000563cdf5db933 in PostgresMain ()
#16 0x0000563cdf547f8c in ?? ()
#17 0x0000563cdf54919a in PostmasterMain ()
#18 0x0000563cdf251ac2 in main ()
```

**Comment by fazalmajid** [comment]
Yes, this extension was originally written for PG 9.2 and last tested on PG 10. The trace you are showing is an error in calculating the size of the argon2 object, probably a null pointer or such. At this point, considering this is really old code and Apsalar was bought and Singular no longer uses this code, I would advise you instead to use something like PL/PythonU to call argon2_cffi instead. If I ever get to fix this, I will let you know in this ticket.

**Comment by carlos-moreira** [comment]
Thank you, just so you know why I'm looking for this extension after all, its because on my company there is a project using argon2 as a hash mechanism, and I'd like to provide to the db team a way for them to easily generate those hashs directly on PostgreSQL.

**Comment by fazalmajid** [comment]
I figured. That was our use-case as well, but after the acquisition the source of truth moved from our PostgreSQL to their (shudder) MySQL.
